<a href="https://colab.research.google.com/github/baeseungyou/baeseungyou/blob/main/%EC%8B%A4%EC%8A%B5%EA%B3%BC%EC%A0%9C_06_20225169_%EB%B0%B0%EC%8A%B9%EC%9C%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([[1],
              [2],
              [3]])
print("A =", A)
print("v =", v)

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
v = [[1]
 [2]
 [3]]


In [ ]:
import numpy as np

a = np.zeros((2,3))
print("a =", a)

b = np.ones((2, 2))
print("b = ", b)

c = np.full((3, 2), 3)
print("c =", c)

d = np.eye(2)
print("d =", d)

a = [[0. 0. 0.]
 [0. 0. 0.]]
b =  [[1. 1.]
 [1. 1.]]
c = [[3 3]
 [3 3]
 [3 3]]
d = [[1. 0.]
 [0. 1.]]


20225169_배승유

In [ ]:
import numpy as np

print("벡터의 결합에 의한 행렬 생성")
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

A = np.vstack([v1, v2, v3]) #v1, v2, v3를 각각 행으로 하는 행렬 A 생성
print("A = ", A)

B = np.column_stack([v1, v2, v3]) #v1, v2, v3를 각각 열로 하는 행렬 B 생성
print("B = ", B)

C = np.array([[1, 2], [3, 4], [5, 6]])
print("C =", C)

D = np.column_stack([C, v3]) #행렬 C에 v3를 열로 추가하여 행렬 D 생성
print("D =", D)

print("행렬의 성분 접근")
E = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("E[0,3]= ", E[0,3])  #1행 4열의 성분
print("E[1,2]= ", E[1,2])  #2행 3열의 성분

print("E[0:2, 2] =", E[0:2, 2]) #E의 1~2행의 3열에 해당하는 부분행렬
print("E[0:2, 2:4] =", E[0:2, 2:4]) #E의 1~2행의 3~4열에 해당하는 부분행렬
print("E[2, :] =", E[2, :]) #E의 3행에 해당하는 부분행렬

print("성분의 변경")
print("E =" , E)

print("E[0,0] = " , E[0, 0])
E[0, 0] = -1    #E의 1행 1열 성분을 -1로 변경
print(E)
print("E[0,0] = " , E[0, 0])



벡터의 결합에 의한 행렬 생성
A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
B =  [[1 4 7]
 [2 5 8]
 [3 6 9]]
C = [[1 2]
 [3 4]
 [5 6]]
D = [[1 2 7]
 [3 4 8]
 [5 6 9]]
행렬의 성분 접근
E[0,3]=  4
E[1,2]=  7
E[0:2, 2] = [3 7]
E[0:2, 2:4] = [[3 4]
 [7 8]]
E[2, :] = [ 9 10 11 12]
성분의 변경
E = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
E[0,0] =  1
[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
E[0,0] =  -1


In [3]:
import numpy as np

# 행렬 A를 출력하는 함수

def pprint(msg, A):
  print("---", msg, "---")
  (n,m) = A.shape
  for i in range(0, n):
    line = ""
    for j in range(0, m):
      line += "{0:.2f}".format(A[i,j]) + "\t"
      print(line)
      print("")

  A = np.array([[1., 2.], [3., 4.]])
  B = np.array([[2., 2.], [1., 3.]])
  C = np.array([[4., 5., 6.], [7., 8., 9.]])
  v = np.array([[10.], [20.]])

  pprint("A+B", A+B) #행렬의 합 A+B 
  pprint("A=B", A-B) #행렬의 차 A-B

  pprint("3*A" , 3*A) #행렬의 스칼라배 3A
  pprint("2*v" , 2*v) #벡터의 스칼라배 2v

  pprint("matmul(A,B)", np.matmul(A,B)) #행렬의 곱 AB
  pprint("matmul(A,C)", np.matmul(A,C)) #행렬의 곱 AC
  pprint("A*v", A*v) #행렬과 벡터의 곱 Av

  pprint("matrix_power(A,2)", np.linalg.matrix_power(A,2)) #행렬의 거듭제곱 A2
  pprint("matrix_power(A,3)", np.linalg.matrix_power(A,3)) #행렬의 거듭제곱 A3

  pprint ("A*B", A*B) #행렬의 성분별 곱셈 A*B
  pprint("A/B" , A/B) #행렬의 성분별 나눗셈 A/B
  pprint("A**2 == A*A", A**2) #행렬의 성분별 거듭제곱 A**2

  pprint("A.T", A.T) #행렬의 전치 AT
  pprint("v.T", v.T) #벡터의 전치 vT

  M = np.diag([1, 2, 3]) #대각행렬 diag(1,2,3) 생성
  pprint("diag(1,2,3) = ", M)

  D11 = np.array([[1, 2], [3, 4]])
  D12 = np.array([[5], [6]])
  D21 = np.array([[7, 7]])
  D22 = np.array([[8]])
  D = np.block([[D11, D12], [D21, D22]]) #블록행렬 D 생성
  pprint("block matrix", D)